In [1]:
import numpy as np
import pandas as pd

In [2]:
deliveries = pd.read_csv(r'deliveries.csv')
matches = pd.read_csv('matches.csv')

In [3]:
print("The shape of delivery dataset is ", deliveries.shape)
print("The shape of delivery dataset is ", matches.shape)

The shape of delivery dataset is  (260920, 17)
The shape of delivery dataset is  (1095, 20)

In [4]:
deliveries.head(5)

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [5]:
matches.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [6]:
matches['team1'].unique()

array(['Royal Challengers Bangalore', 'Kings XI Punjab',
       'Delhi Daredevils', 'Mumbai Indians', 'Kolkata Knight Riders',
       'Rajasthan Royals', 'Deccan Chargers', 'Chennai Super Kings',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Gujarat Lions', 'Rising Pune Supergiants',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Lucknow Super Giants', 'Gujarat Titans',
       'Royal Challengers Bengaluru'], dtype=object)

In [7]:
teams = {
    'Royal Challengers Bengaluru',
    'Gujarat Titans',
    'Punjab Kings',
    'Delhi Capitals',
    'Sunrisers Hyderabad',
    'Chennai Super Kings',
    'Rajasthan Royals',
    'Kolkata Knight Riders',
    'Mumbai Indians',
    'Lucknow Super Giants'
}

In [8]:
match_df = matches.copy()

In [9]:
match_df.head(3)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar

### Replacing teams old names with new names

In [10]:
match_df['team1'] = matches['team1'].str.replace('Delhi Daredevils', 'Delhi Capitals') \
                                    .str.replace('Royal Challengers Bangalore', 'Royal Challengers Bengaluru') \
                                    .str.replace('Kings XI Punjab', 'Punjab Kings') \
                                    .str.replace('Deccan Chargers', 'Sunrisers Hyderabad')

match_df['team2'] = matches['team2'].str.replace('Delhi Daredevils', 'Delhi Capitals') \
                                    .str.replace('Royal Challengers Bangalore', 'Royal Challengers Bengaluru') \
                                    .str.replace('Kings XI Punjab', 'Punjab Kings') \
                                    .str.replace('Deccan Chargers', 'Sunrisers Hyderabad')

match_df['toss_winner'] = matches['toss_winner'].str.replace('Delhi Daredevils', 'Delhi Capitals') \
                                    .str.replace('Royal Challengers Bangalore', 'Royal Challengers Bengaluru') \
                                    .str.replace('Kings XI Punjab', 'Punjab Kings') \
                                    .str.replace('Deccan Chargers', 'Sunrisers Hyderabad')

In [11]:
match_df.head(3)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bengaluru,Kolkata Knight Riders,Royal Challengers Bengaluru,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Punjab Kings,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Capitals,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar

#### Removing matches in which DLS used

In [12]:
match_df=match_df[match_df['method']!='D/L']

#### Merging both dataFrames on match id

In [13]:
match_df= match_df[['id','city','winner','target_runs']]

In [14]:
data = match_df.merge(deliveries,left_on='id',right_on='match_id')

In [15]:
data.head()

,id,city,winner,target_runs,match_id,inning,batting_team,bowling_team,over,ball,...,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,Bangalore,Kolkata Knight Riders,223.0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,Bangalore,Kolkata Knight Riders,223.0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,Bangalore,Kolkata Knight Riders,223.0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,Bangalore,Kolkata Knight Riders,223.0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,Bangalore,Kolkata Knight Riders,223.0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,...,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 257274 entries, 0 to 257273
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                257274 non-null  int64
 1   city              244877 non-null  object
 2   winner            256784 non-null  object
 3   target_runs       256965 non-null  float64
 4   match_id          257274 non-null  int64
 5   inning            257274 non-null  int64
 6   batting_team      257274 non-null  object
 7   bowling_team      257274 non-null  object
 8   over              257274 non-null  int64
 9   ball              257274 non-null  int64
 10  batter            257274 non-null  object
 11  bowler            257274 non-null  object
 12  non_striker       257274 non-null  object
 13  batsman_runs      257274 non-null  int64
 14  extra_runs        257274 non-null  int64
 15  total_runs        257274 non-null  int64
 16  extras_type       13910 non-null   object
 17  is_wicket         257274 non-null  int64
 18  player_dismissed  12774 non-null   object
 19  dismissal_kind    12774 non-null   object
 20  fielder           9215 non-null    object
dtypes: float64(1), int64(9), object(11)
memory usage: 41.2+ MB

In [17]:
data.shape

(257274, 21)

In [18]:
data.drop('match_id',axis=1,inplace=True)

In [19]:
data.head(3)

,id,city,winner,target_runs,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,Bangalore,Kolkata Knight Riders,223.0,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,Bangalore,Kolkata Knight Riders,223.0,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,Bangalore,Kolkata Knight Riders,223.0,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN

In [20]:
data.shape

(257274, 20)

#### Fetching only 2nd inning data

In [21]:
data=data[data['inning']==2]

In [22]:
data.shape

(124387, 20)

In [23]:
data.head(2)

,id,city,winner,target_runs,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
124,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,1,R Dravid,AB Dinda,W Jaffer,1,0,1,NaN,0,NaN,NaN,NaN
125,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,2,W Jaffer,AB Dinda,R Dravid,0,1,1,wides,0,NaN,NaN,NaN

#### Making two new columns runs left and balls left

In [24]:
# Calculating current score
data['current_score']=data.groupby('id')['total_runs'].cumsum()

In [25]:
data.head()

,id,city,winner,target_runs,inning,batting_team,bowling_team,over,ball,batter,...,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,current_score
124,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,1,R Dravid,...,W Jaffer,1,0,1,NaN,0,NaN,NaN,NaN,1
125,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,2,W Jaffer,...,R Dravid,0,1,1,wides,0,NaN,NaN,NaN,2
126,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,3,W Jaffer,...,R Dravid,0,0,0,NaN,0,NaN,NaN,NaN,2
127,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,4,W Jaffer,...,R Dravid,1,0,1,NaN,0,NaN,NaN,NaN,3
128,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,5,R Dravid,...,W Jaffer,1,0,1,NaN,0,NaN,NaN,NaN,4

In [26]:
# calculating runs required 
data['runs_required'] = data['target_runs']-data['current_score']
data.head()

,id,city,winner,target_runs,inning,batting_team,bowling_team,over,ball,batter,...,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,current_score,runs_required
124,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,1,R Dravid,...,1,0,1,NaN,0,NaN,NaN,NaN,1,222.0
125,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,2,W Jaffer,...,0,1,1,wides,0,NaN,NaN,NaN,2,221.0
126,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,3,W Jaffer,...,0,0,0,NaN,0,NaN,NaN,NaN,2,221.0
127,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,4,W Jaffer,...,1,0,1,NaN,0,NaN,NaN,NaN,3,220.0
128,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,5,R Dravid,...,1,0,1,NaN,0,NaN,NaN,NaN,4,219.0

#### Calculating number of balls left after every ball

In [27]:
max_balls = 120  # Initialize the total number of balls

# Check if the delivery is either wides or noballs
curr_id = 335982
data['balls_left'] = max_balls 
for index, row in data.iterrows():
    if curr_id==row['id']:

        if row['extras_type'] in ['wides', 'noballs']:  # Check for wide or no-ball in the row
            data.at[index, 'balls_left'] = max_balls  # Do not decrement if wide or no-ball
        else:
            max_balls -= 1 
            data.at[index, 'balls_left'] = max_balls 
    else:
        max_balls=120
        curr_id = row['id']
        if row['extras_type'] in ['wides', 'noballs']:  # Check for wide or no-ball in the row
            data.at[index, 'balls_left'] = max_balls  # Do not decrement if wide or no-ball
        else:
            max_balls -= 1 
            data.at[index, 'balls_left'] = max_balls

#### Calculating wicket left

In [28]:
data.columns

Index(['id', 'city', 'winner', 'target_runs', 'inning', 'batting_team',
       'bowling_team', 'over', 'ball', 'batter', 'bowler', 'non_striker',
       'batsman_runs', 'extra_runs', 'total_runs', 'extras_type', 'is_wicket',
       'player_dismissed', 'dismissal_kind', 'fielder', 'current_score',
       'runs_required', 'balls_left'],
      dtype='object')

In [29]:
wickets=data.groupby('id')['is_wicket'].cumsum().values
data['wickets_left'] = 10 - wickets

In [30]:
data.head(2)

,id,city,winner,target_runs,inning,batting_team,bowling_team,over,ball,batter,...,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,current_score,runs_required,balls_left,wickets_left
124,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,1,R Dravid,...,1,NaN,0,NaN,NaN,NaN,1,222.0,119,10
125,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,2,W Jaffer,...,1,wides,0,NaN,NaN,NaN,2,221.0,119,10

#### Creating columns like current run rate and required run rate

In [31]:
data['crr'] = (data['current_score']*6/(120 - data['balls_left'])).round(2)
data['rrr'] = (data['runs_required']*6/(data['balls_left'])).round(2)

In [32]:
data.head(1)

,id,city,winner,target_runs,inning,batting_team,bowling_team,over,ball,batter,...,is_wicket,player_dismissed,dismissal_kind,fielder,current_score,runs_required,balls_left,wickets_left,crr,rrr
124,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,1,R Dravid,...,0,NaN,NaN,NaN,1,222.0,119,10,6.0,11.19

##### Creating column win

In [33]:
data['result'] = (data['winner'] == data['batting_team']).astype(int)

In [34]:
data.head(2)

,id,city,winner,target_runs,inning,batting_team,bowling_team,over,ball,batter,...,player_dismissed,dismissal_kind,fielder,current_score,runs_required,balls_left,wickets_left,crr,rrr,result
124,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,1,R Dravid,...,NaN,NaN,NaN,1,222.0,119,10,6.0,11.19,0
125,335982,Bangalore,Kolkata Knight Riders,223.0,2,Royal Challengers Bangalore,Kolkata Knight Riders,0,2,W Jaffer,...,NaN,NaN,NaN,2,221.0,119,10,12.0,11.14,0

In [35]:
# Taking only those columns which are required 
df=data[['city','batting_team','bowling_team','target_runs','current_score','runs_required','balls_left','wickets_left','crr','rrr','result']]

In [36]:
df.shape

(124387, 11)

In [37]:
df.head(2)

,city,batting_team,bowling_team,target_runs,current_score,runs_required,balls_left,wickets_left,crr,rrr,result
124,Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,223.0,1,222.0,119,10,6.0,11.19,0
125,Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,223.0,2,221.0,119,10,12.0,11.14,0

#### Shuffling data to make randomness in the data

In [38]:
df = df.sample(df.shape[0])

In [39]:
df.head(5)

,city,batting_team,bowling_team,target_runs,current_score,runs_required,balls_left,wickets_left,crr,rrr,result
157961,Delhi,Royal Challengers Bangalore,Delhi Daredevils,182.0,156,26.0,20,6,9.36,7.80,1
80984,Hyderabad,Sunrisers Hyderabad,Kings XI Punjab,124.0,48,76.0,75,9,6.40,6.08,1
73208,Dharamsala,Delhi Daredevils,Kings XI Punjab,142.0,21,121.0,102,10,7.00,7.12,1
61424,Bangalore,Royal Challengers Bangalore,Rajasthan Royals,196.0,78,118.0,58,7,7.55,12.21,0
2791,Chennai,Chennai Super Kings,Kolkata Knight Riders,148.0,74,74.0,64,9,7.93,6.94,1

In [40]:
df.shape

(124387, 11)

#### Checking null values

In [41]:
print(df.shape)
df.isnull().sum()

(124387, 11)

city             6012
batting_team        0
bowling_team        0
target_runs         0
current_score       0
runs_required       0
balls_left          0
wickets_left        0
crr                 0
rrr                20
result              0
dtype: int64

In [42]:
df.dropna(inplace=True)

In [43]:
print(df.shape)
df.isnull().sum()

(118355, 11)

city             0
batting_team     0
bowling_team     0
target_runs      0
current_score    0
runs_required    0
balls_left       0
wickets_left     0
crr              0
rrr              0
result           0
dtype: int64

In [44]:
df.describe()

c:\Users\91702\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
c:\Users\91702\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\_methods.py:49: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)

,target_runs,current_score,runs_required,balls_left,wickets_left,crr,rrr,result
count,118355.000000,118355.000000,118355.000000,118355.000000,118355.000000,118355.00,118355.00,118355.000000
mean,168.683233,74.737797,93.945435,62.749204,7.500410,inf,NaN,0.520713
std,30.657738,47.679418,50.829576,33.426986,2.160716,NaN,NaN,0.499573
min,63.000000,0.000000,-5.000000,-1.000000,0.000000,0.00,-inf,0.000000
25%,149.000000,35.000000,54.000000,35.000000,6.000000,6.41,7.29,0.000000
50%,168.000000,71.000000,93.000000,63.000000,8.000000,7.64,9.00,1.000000
75%,188.000000,110.000000,132.000000,92.000000,9.000000,8.91,11.18,1.000000
max,288.000000,262.000000,287.000000,120.000000,10.000000,inf,inf,1.000000

#### Removing last ball data because it is creating a error that infinite will at required run rate come as 0 balls left and some runs are required

In [45]:
df=df[df['balls_left']!=0]

##### Also removing those first balls when a wide or no ball is bowled

In [46]:
df=df[df['balls_left']!=120]

In [47]:
df.describe()

,target_runs,current_score,runs_required,balls_left,wickets_left,crr,rrr,result
count,117903.000000,117903.000000,117903.000000,117903.000000,117903.000000,117903.000000,117903.000000,117903.000000
mean,168.644318,74.507298,94.137019,62.917500,7.514287,7.645036,10.737360,0.522167
std,30.659831,47.468338,50.711896,33.270423,2.145205,2.416211,13.315893,0.499511
min,63.000000,0.000000,-5.000000,-1.000000,0.000000,0.000000,-360.000000,0.000000
25%,149.000000,35.000000,54.000000,35.000000,6.000000,6.410000,7.280000,0.000000
50%,168.000000,71.000000,93.000000,63.000000,8.000000,7.640000,9.000000,1.000000
75%,188.000000,110.000000,132.000000,92.000000,9.000000,8.910000,11.140000,1.000000
max,288.000000,262.000000,287.000000,119.000000,10.000000,60.000000,792.000000,1.000000

In [48]:
x = df.iloc[:,0:-1]
y = df.iloc[:,-1]
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [49]:
print("The shape of X_train is ",X_train.shape)
print("The shape of X_test is ",X_test.shape)
print("The shape of Y_train is ",Y_train.shape)
print("The shape of Y_test is ",Y_test.shape)

The shape of X_train is  (94322, 10)
The shape of X_test is  (23581, 10)
The shape of Y_train is  (94322,)
The shape of Y_test is  (23581,)

In [50]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

trf = ColumnTransformer(transformers=[
    ('trf', OneHotEncoder(sparse_output=False, drop='first'), ['batting_team', 'bowling_team', 'city'])
], remainder='passthrough')

In [51]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
pipe = Pipeline(steps=[
    ('step1',trf),
    ('step2',LogisticRegression(solver='liblinear'))
])

In [52]:
pipe.fit(X_train,Y_train)

c:\Users\91702\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\compose\_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [53]:
y_pred = pipe.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,y_pred)

0.8103133878970358

#### Checking for SVM

In [349]:
from sklearn.svm import SVC
pipe2 = Pipeline(steps=[
    ('step1',trf),
    ('step2',SVC(kernel='rbf', C=1.0, gamma='scale'))
])
pipe2.fit(X_train,Y_train)

c:\Users\91702\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\compose\_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', SVC())])

In [350]:
y_pred2 = pipe2.predict(X_test)
accuracy_score(Y_test,y_pred2)

0.7791442262838726

#### Checking whole match condition after each over

In [70]:
def match_progression(data,match_id,pipe):
    match = data[data['id'] == match_id]

    match = match[(match['ball'] == 6)]
    temp_df = match[['batting_team','bowling_team','city','runs_required','balls_left','wickets_left','target_runs','crr','rrr','current_score']].dropna()
    temp_df = temp_df[temp_df['balls_left'] != 0]
    result = pipe.predict_proba(temp_df)
    temp_df['lose'] = np.round(result.T[0]*100,1)
    temp_df['win'] = np.round(result.T[1]*100,1)
    temp_df['end_of_over'] = range(1,temp_df.shape[0]+1)
    
    target = temp_df['target_runs'].values[0]
    runs = list(temp_df['runs_required'].values)
    new_runs = runs[:]
    runs.insert(0,target)
    temp_df['runs_after_over'] = np.array(runs)[:-1] - np.array(new_runs)
    wickets = list(temp_df['wickets_left'].values)
    new_wickets = wickets[:]
    new_wickets.insert(0,10)
    wickets.append(0)
    w = np.array(wickets)
    nw = np.array(new_wickets)
    temp_df['wickets_in_over'] = (nw - w)[0:temp_df.shape[0]]
    
    print("Target-",target)
    temp_df = temp_df[['end_of_over','runs_after_over','wickets_in_over','lose','win']]
    return temp_df,target

In [71]:
temp_df,target = match_progression(data,335982,pipe)
temp_df

Target- 223.0

     end_of_over  runs_after_over  wickets_in_over   lose  win
129            1              4.0                0   90.6  9.4
136            2              5.0                1   94.8  5.2
142            3              2.0                1   97.4  2.6
149            4              5.0                0   97.7  2.3
155            5              8.0                1   98.5  1.5
161            6              2.0                1   99.3  0.7
167            7              3.0                0   99.4  0.6
175            8              9.0                1   99.7  0.3
181            9              3.0                1   99.8  0.2
189           10              9.0                1   99.9  0.1
196           11              6.0                0   99.9  0.1
202           12              3.0                1  100.0  0.0
208           13             10.0                0  100.0  0.0
215           14              8.0                1  100.0  0.0
221           15              4.0                0  100.0  0.0

In [355]:
# Teams
teams

{'Chennai Super Kings',
 'Delhi Capitals',
 'Gujarat Titans',
 'Kolkata Knight Riders',
 'Lucknow Super Giants',
 'Mumbai Indians',
 'Punjab Kings',
 'Rajasthan Royals',
 'Royal Challengers Bengaluru',
 'Sunrisers Hyderabad'}

In [356]:
# city 
data['city'].unique()

array(['Bangalore', 'Chandigarh', 'Delhi', 'Mumbai', 'Kolkata', 'Jaipur',
       'Hyderabad', 'Chennai', 'Cape Town', 'Port Elizabeth', 'Durban',
       'Centurion', 'East London', 'Johannesburg', 'Kimberley',
       'Bloemfontein', 'Ahmedabad', 'Cuttack', 'Nagpur', 'Dharamsala',
       'Kochi', 'Indore', 'Visakhapatnam', 'Pune', 'Raipur', 'Ranchi',
       'Abu Dhabi', nan, 'Rajkot', 'Kanpur', 'Bengaluru', 'Dubai',
       'Sharjah', 'Navi Mumbai', 'Lucknow', 'Guwahati', 'Mohali'],
      dtype=object)

In [361]:
import pickle 
pickle.dump(pipe,open('pipe.pkl','wb'))